# Customer Success FTE - Channel Formatters
# Format responses appropriately for each channel

from enum import Enum
from typing import Optional


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


# =============================================================================
# CHANNEL CONSTANTS
# =============================================================================

CHANNEL_LIMITS = {
    Channel.EMAIL: {"max_words": 500, "max_chars": 3000},
    Channel.WHATSAPP: {"max_chars": 300, "max_chars_soft": 160},
    Channel.WEB_FORM: {"max_words": 300, "max_chars": 1800},
}

# =============================================================================
# MAIN FORMATTER
# =============================================================================


def format_for_channel(
    message: str,
    channel: str,
    ticket_id: Optional[str] = None,
    customer_name: Optional[str] = None
) -> str:
    """
    Format response appropriately for the target channel.

    Args:
        message: The core response message
        channel: Target channel (email, whatsapp, web_form)
        ticket_id: Optional ticket ID for reference
        customer_name: Optional customer name for personalization

    Returns:
        Formatted response string
    """
    channel_enum = Channel(channel) if isinstance(channel, str) else channel

    if channel_enum == Channel.EMAIL:
        return _format_email(message, ticket_id, customer_name)
    elif channel_enum == Channel.WHATSAPP:
        return _format_whatsapp(message, ticket_id)
    else:  # WEB_FORM
        return _format_web_form(message, ticket_id, customer_name)


def _format_email(
    message: str,
    ticket_id: Optional[str] = None,
    customer_name: Optional[str] = None
) -> str:
    """Format response for email - formal with greeting and signature."""

    # Greeting
    if customer_name:
        greeting = f"Dear {customer_name},"
    else:
        greeting = "Dear Customer,"

    # Opening
    opening = "Thank you for reaching out to TechCorp Support."

    # Truncate if too long (500 words max)
    words = message.split()
    if len(words) > 500:
        message = " ".join(words[:500])
        # Add note about truncation
        message = message.rstrip(".") + "..."

    # Closing
    closing = "If you have any further questions, please don't hesitate to reply to this email."

    # Signature
    signature = "Best regards,\nTechCorp AI Support Team"

    # Build email
    email_parts = [greeting, "", opening, "", message, "", closing, "", signature]

    # Add ticket reference if provided
    if ticket_id:
        email_parts.extend(["---", f"Ticket Reference: {ticket_id}", ""])
        email_parts.append("This response was generated by our AI assistant. For complex issues, you can request human support.")

    return "\n".join(email_parts)


def _format_whatsapp(message: str, ticket_id: Optional[str] = None) -> str:
    """Format response for WhatsApp - concise and conversational."""

    # Truncate if too long (300 chars hard limit)
    if len(message) > 300:
        # Try to find a good break point
        break_point = message.rfind(". ", 0, 280)
        if break_point == -1:
            break_point = message.rfind(" ", 0, 280)
        if break_point == -1:
            break_point = 280
        message = message[:break_point + 1].strip() + "..."

    # Build response
    response = message

    # Add call-to-action
    cta = "\n\n📱 Reply for more help or type 'human' for live support."
    response += cta

    # Add ticket reference if provided (shortened)
    if ticket_id:
        response += f" | Ref: {ticket_id}"

    return response


def _format_web_form(
    message: str,
    ticket_id: Optional[str] = None,
    customer_name: Optional[str] = None
) -> str:
    """Format response for web form - semi-formal, helpful."""

    # Greeting (more casual than email)
    if customer_name:
        greeting = f"Hi {customer_name}!"
    else:
        greeting = "Thanks for contacting TechCorp Support!"

    # Truncate if too long (300 words max)
    words = message.split()
    if len(words) > 300:
        message = " ".join(words[:300])
        message = message.rstrip(".") + "..."

    # Closing
    closing = "Need more help? Reply to this message or visit our support portal."

    # Build response
    response_parts = [greeting, "", message, "", "---", closing]

    # Add ticket reference if provided
    if ticket_id:
        response_parts.append(f"Ticket: {ticket_id}")

    return "\n".join(response_parts)


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================


def truncate_to_words(text: str, max_words: int) -> str:
    """Truncate text to maximum word count."""
    words = text.split()
    if len(words) <= max_words:
        return text

    truncated = " ".join(words[:max_words])
    # Try to end at sentence boundary
    last_period = truncated.rfind(".")
    if last_period > max_words * 3:  # Only if we don't lose too much
        return truncated[:last_period + 1]

    return truncated.rstrip() + "..."


def truncate_to_chars(text: str, max_chars: int, break_on_word: bool = True) -> str:
    """Truncate text to maximum character count."""
    if len(text) <= max_chars:
        return text

    if break_on_word:
        # Find last word boundary
        break_point = text.rfind(" ", 0, max_chars)
        if break_point == -1:
            break_point = max_chars
        return text[:break_point].rstrip() + "..."
    else:
        return text[:max_chars - 3] + "..."


def count_words(text: str) -> int:
    """Count words in text."""
    return len(text.split())


def estimate_reading_time(text: str, words_per_minute: int = 200) -> float:
    """Estimate reading time in seconds."""
    words = count_words(text)
    return (words / words_per_minute) * 60
